version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - COINGECKO_SERVICE_URL=http://coingecko:8001
    depends_on:
      - redis
      - coingecko
    networks:
      - crypto_network

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - crypto_network

  coingecko:
    build:
      context: ./services/coingecko
      dockerfile: Dockerfile
    ports:
      - "8001"  # Only specify the container port, let Docker assign host ports dynamically
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - crypto_network
    deploy:
      replicas: 2  # Run 2 instances of the service for testing
      restart_policy:
        condition: on-failure

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - crypto_network

volumes:
  redis_data:

networks:
  crypto_network:
    driver: bridge 